apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert -f .\docker-compose.yml --out menifest/
    kompose.version: 1.35.0 (9532ceef3)
  labels:
    io.kompose.service: aspire
  name: aspire
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: aspire
  template:
    metadata:
      annotations:
        kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert -f .\docker-compose.yml --out menifest/
        kompose.version: 1.35.0 (9532ceef3)
      labels:
        io.kompose.service: aspire
    spec:
      serviceAccountName: default  # Set a service account if needed
      automountServiceAccountToken: false
      containers:
        - name: aspire-dashboard
          image: mcr.microsoft.com/dotnet/aspire-dashboard:8.0  # Use a specific version instead of 'latest'
          ports:
            - containerPort: 18888
              protocol: TCP
          resources:
            requests:
              cpu: "250m"         # Minimum CPU request
              memory: "256Mi"     # Minimum memory request
              ephemeral-storage: "512Mi"  # Minimum storage request
            limits:
              cpu: "500m"         # Maximum CPU limit
              memory: "512Mi"     # Maximum memory limit
              ephemeral-storage: "1Gi"  # Maximum storage limit
          livenessProbe:
            exec:
              command:
                - curl
                - --silent
                - --fail
                - http://localhost:18888/metrics
            failureThreshold: 5
            periodSeconds: 10
      restartPolicy: Always
