apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert -f .\docker-compose.yml --out menifest/
    kompose.version: 1.35.0 (9532ceef3)
  labels:
    io.kompose.service: backend
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: backend
  template:
    metadata:
      annotations:
        kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert -f .\docker-compose.yml --out menifest/
        kompose.version: 1.35.0 (9532ceef3)
      labels:
        io.kompose.service: backend
    spec:
      serviceAccountName: default  # Set a service account if needed
      automountServiceAccountToken: false
      containers:
        - name: backend-container
          image: backend-image:v1.0  # Use a specific version instead of latest/untagged
          imagePullPolicy: Never
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: Development
            - name: ASPNETCORE_URLS
              value: https://+:8000
            - name: ConnectionStrings__DefaultConnection
              value: Host=postgres;Port=5432;Database=TalentMesh;Username=postgres;Password=postgres
            - name: DOTNET_DASHBOARD_URL
              value: https://aspire:18888
            - name: RabbitMQ__Host
              value: rabbitmq
            - name: RabbitMQ__Password
              value: guest
            - name: RabbitMQ__Port
              value: "5672"
            - name: RabbitMQ__Username
              value: guest
            - name: Redis__Host
              value: redis
            - name: Redis__Port
              value: "6379"
          ports:
            - containerPort: 8000
              protocol: TCP
          resources:
            requests:
              cpu: "250m"         # Minimum CPU request
              memory: "256Mi"     # Minimum memory request
              ephemeral-storage: "512Mi"  # Minimum storage request
            limits:
              cpu: "500m"         # Maximum CPU limit
              memory: "512Mi"     # Maximum memory limit
              ephemeral-storage: "1Gi"  # Maximum storage limit
          livenessProbe:
            exec:
              command:
                - curl
                - --silent
                - --fail
                - http://localhost:8000/metrics
            failureThreshold: 5
            periodSeconds: 10
      restartPolicy: Always
