apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert -f .\docker-compose.yml --out menifest/
    kompose.version: 1.35.0 (9532ceef3)
  labels:
    io.kompose.service: node-exporter
  name: node-exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: node-exporter
  template:
    metadata:
      annotations:
        kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert -f .\docker-compose.yml --out menifest/
        kompose.version: 1.35.0 (9532ceef3)
      labels:
        io.kompose.service: node-exporter
    spec:
      automountServiceAccountToken: false  # ✅ Fix: Disable service account automounting
      containers:
        - image: prom/node-exporter:v1.6.1  # ✅ Fix: Use a specific image version
          name: node-exporter
          ports:
            - containerPort: 9100
              protocol: TCP
          resources:
            requests:
              cpu: "100m"                 # ✅ Fix: Specify CPU request
              memory: "128Mi"             # ✅ Fix: Specify memory request
              ephemeral-storage: "1Gi"    # ✅ Fix: Specify storage request
            limits:
              memory: "256Mi"             # ✅ Fix: Specify memory limit
      restartPolicy: Always
