apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  labels:
    io.kompose.service: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: postgres
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        io.kompose.service: postgres
    spec:
      automountServiceAccountToken: false
      containers:
        - name: postgres-db
          image: postgres:15.3
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: TalentMesh
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PASSWORD
              value: postgres
          livenessProbe:
            exec:
              command:
                - pg_isready
                - -U
                - postgres
                - -d
                - TalentMesh
            failureThreshold: 5
            periodSeconds: 10
          resources:
            requests:
              cpu: "250m"
              memory: "512Mi"
              ephemeral-storage: "1Gi"  # ✅ Corrected storage request
            limits:
              memory: "1Gi"
              ephemeral-storage: "2Gi"  # ✅ Corrected storage limit
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgres-data
      restartPolicy: Always
      volumes:
        - name: postgres-data
          persistentVolumeClaim:
            claimName: postgres-data-new  # PVC name must match

---
# PostgreSQL PersistentVolumeClaim (PVC)
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-data-new
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  resources:
    requests:
      storage: 1Gi  # ✅ PVC storage request
