apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus
  labels:
    io.kompose.service: prometheus
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: prometheus
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        io.kompose.service: prometheus
    spec:
      automountServiceAccountToken: false
      containers:
        - name: prometheus
          image: prom/prometheus:v2.44.0
          ports:
            - containerPort: 9090
              protocol: TCP
          resources:
            requests:
              cpu: "100m"
              memory: "512Mi"
              ephemeral-storage: "1Gi"  # ✅ Use ephemeral-storage instead of "storage"
            limits:
              memory: "1Gi"
              ephemeral-storage: "2Gi"
          volumeMounts:
            - mountPath: /etc/prometheus/prometheus.yml
              name: prometheus-config
              subPath: prometheus.yml
            - mountPath: /prometheus
              name: prometheus-data
      restartPolicy: Always
      volumes:
        - name: prometheus-config
          configMap:
            name: prometheus-cm0
            items:
              - key: prometheus.yml
                path: prometheus.yml
        - name: prometheus-data
          persistentVolumeClaim:
            claimName: prometheus-data

---
# Prometheus PersistentVolumeClaim (PVC)
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prometheus-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi  # ✅ Fixed PVC storage request