apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert -f .\docker-compose.yml --out menifest/
    kompose.version: 1.35.0 (9532ceef3)
  labels:
    io.kompose.service: backend
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: backend
  template:
    metadata:
      annotations:
        kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert -f .\docker-compose.yml --out menifest/
        kompose.version: 1.35.0 (9532ceef3)
      labels:
        io.kompose.service: backend
    spec:
      containers:
        - env:
            - name: ASPNETCORE_ENVIRONMENT
              value: Development
            - name: ASPNETCORE_URLS
              value: http://+:8000
            - name: ConnectionStrings__DefaultConnection
              value: Host=postgres;Port=5432;Database=ecommerce-cart;Username=postgres;Password=postgres
            - name: Redis__Host
              value: redis
            - name: Redis__Port
              value: "6379"
          image: mdnafiulhasanhamim/backend-image:latest
          name: backend-container
          imagePullPolicy: Never
          ports:
            - containerPort: 8000
              protocol: TCP
      restartPolicy: Always
